// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz-zudVZZOpedandNiHzyE0Z3Kbg5yxMM',
    appId: '1:758162295054:web:369f4f1081a415466bef5f',
    messagingSenderId: '758162295054',
    projectId: 'mainproject-e1bda',
    authDomain: 'mainproject-e1bda.firebaseapp.com',
    storageBucket: 'mainproject-e1bda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgB2geo3wp12mfuCZPGIfYvwZ6c2aTb10',
    appId: '1:758162295054:android:329c787b2afd12d16bef5f',
    messagingSenderId: '758162295054',
    projectId: 'mainproject-e1bda',
    storageBucket: 'mainproject-e1bda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA18GGLMxmJrDd0pWFkmxFotYy7_X7ncrw',
    appId: '1:758162295054:ios:dc886c4ee373c6516bef5f',
    messagingSenderId: '758162295054',
    projectId: 'mainproject-e1bda',
    storageBucket: 'mainproject-e1bda.firebasestorage.app',
    iosBundleId: 'com.example.mainProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA18GGLMxmJrDd0pWFkmxFotYy7_X7ncrw',
    appId: '1:758162295054:ios:dc886c4ee373c6516bef5f',
    messagingSenderId: '758162295054',
    projectId: 'mainproject-e1bda',
    storageBucket: 'mainproject-e1bda.firebasestorage.app',
    iosBundleId: 'com.example.mainProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz-zudVZZOpedandNiHzyE0Z3Kbg5yxMM',
    appId: '1:758162295054:web:f67f1980a343667c6bef5f',
    messagingSenderId: '758162295054',
    projectId: 'mainproject-e1bda',
    authDomain: 'mainproject-e1bda.firebaseapp.com',
    storageBucket: 'mainproject-e1bda.firebasestorage.app',
  );
}
